
# TECHNICAL SPECIFICATIONS

[General]

Weight: 733 # Kg
Center of gravity height: 0.205 # m
Weight distribution: 46:54 (F:R)
Base drag: 0.32
Fuel tank capacity: 145 L
Speed limiter: Available for 80 Km/h
Number of gears: 8 forward, 1 reverse
Driven wheels: RWD
Steering lock-to-lock: 450 degrees

[Engine]
Aspiration: Turbocharged
Max. Power: 929 hp -> 13250  # rpm
Max. Torque: 510.5 Nm @ 12000  # rpm
Power-to-weight: 1.27 hp/Kg
Rev limit range: [11500, 13000]  # rpm
Optimal oil temp: 107  # C
Max safe oil temp: 114  # C
Safe RPM: 12300  # rpm
Avg. lifetime: 120  # minutes
Lifetime variance: 6 # minutes

Engine.png

Brakes

Optimal brake temp: 300 950 C
Max brake torque: 4890.0 Nm (Front), 3990.0 Nm (Rear)
Half torque temp: 1200 C
Brake disc thickness: 28 32 mm
Disc failure thickness: 22.7 23.3 mm
Onboard brake bias: Available

Brakes (1).png

Tires

Optimal temp for all compounds: 99.85 C